apiVersion: apps/v1
kind: Deployment
metadata:
  name: regional-deployment
  namespace: central-configuration
  labels:
    app: regional-deployment
    component: central-config
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regional-deployment
  template:
    metadata:
      labels:
        app: regional-deployment
        component: central-config
        version: v1
    spec:
      serviceAccountName: regional-deployment-sa
      containers:
      - name: regional-deployment
        image: ghcr.io/exalt/regional-deployment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8187
          name: http
          protocol: TCP
        - containerPort: 8081
          name: management
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8187"
        - name: MANAGEMENT_SERVER_PORT
          value: "8081"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8166"
        - name: EUREKA_SERVER_URL
          value: "http://service-registry:8154/eureka"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: regional-deployment-db-secret
              key: url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: regional-deployment-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: regional-deployment-db-secret
              key: password
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: regional-deployment-config
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - regional-deployment
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: regional-deployment
  namespace: central-configuration
  labels:
    app: regional-deployment
    component: central-config
spec:
  type: ClusterIP
  ports:
  - port: 8187
    targetPort: http
    protocol: TCP
    name: http
  - port: 8081
    targetPort: management
    protocol: TCP
    name: management
  selector:
    app: regional-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regional-deployment-sa
  namespace: central-configuration
  labels:
    app: regional-deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regional-deployment-config
  namespace: central-configuration
  labels:
    app: regional-deployment
data:
  application.yaml: |
    spring:
      application:
        name: regional-deployment
      cloud:
        kubernetes:
          reload:
            enabled: true
            mode: polling
            period: 5000
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      metrics:
        export:
          prometheus:
            enabled: true
    logging:
      level:
        root: INFO
        com.exalt: DEBUG
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: regional-deployment-pdb
  namespace: central-configuration
  labels:
    app: regional-deployment
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: regional-deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: regional-deployment-hpa
  namespace: central-configuration
  labels:
    app: regional-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: regional-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
