# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: regional-deployment-db-secret
  namespace: central-configuration
  labels:
    app: regional-deployment
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/regional_deployment_db"
  username: "regional_deployment_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: regional-deployment-app-secret
  namespace: central-configuration
  labels:
    app: regional-deployment
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
