apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-configuration
  namespace: exalt-dev
  labels:
    app: central-configuration
    domain: configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-configuration
  template:
    metadata:
      labels:
        app: central-configuration
        domain: configuration
    spec:
      containers:
      - name: central-configuration
        image: central-configuration:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: central-configuration
  namespace: exalt-dev
  labels:
    app: central-configuration
spec:
  selector:
    app: central-configuration
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
