# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-as-code-db-secret
  namespace: central-configuration
  labels:
    app: infrastructure-as-code
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/infrastructure_as_code_db"
  username: "infrastructure_as_code_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-as-code-app-secret
  namespace: central-configuration
  labels:
    app: infrastructure-as-code
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
