apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: central-configuration
  labels:
    app: config-server
    domain: central-configuration
spec:
  selector:
    app: config-server
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
