# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: environment-config-db-secret
  namespace: central-configuration
  labels:
    app: environment-config
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/environment_config_db"
  username: "environment_config_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: environment-config-app-secret
  namespace: central-configuration
  labels:
    app: environment-config
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
