# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: secrets-management-db-secret
  namespace: central-configuration
  labels:
    app: secrets-management
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/secrets_management_db"
  username: "secrets_management_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-management-app-secret
  namespace: central-configuration
  labels:
    app: secrets-management
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
