# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-manifests-db-secret
  namespace: central-configuration
  labels:
    app: kubernetes-manifests
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/kubernetes_manifests_db"
  username: "kubernetes_manifests_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-manifests-app-secret
  namespace: central-configuration
  labels:
    app: kubernetes-manifests
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
