# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: deployment-scripts-db-secret
  namespace: central-configuration
  labels:
    app: deployment-scripts
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/deployment_scripts_db"
  username: "deployment_scripts_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: deployment-scripts-app-secret
  namespace: central-configuration
  labels:
    app: deployment-scripts
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
