server:
  port: 8892

spring:
  application:
    name: database-migrations
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  # Database Configuration - Multiple DataSource Support
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/migrations_db}
    username: ${DATABASE_USERNAME:migrations_user}
    password: ${DATABASE_PASSWORD:migrations_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Migration Configuration
migration:
  config:
    target-databases:
      - name: central-config
        url: ${CENTRAL_CONFIG_DB_URL:}
        username: ${CENTRAL_CONFIG_DB_USER:}
        password: ${CENTRAL_CONFIG_DB_PASS:}
      - name: user-management
        url: ${USER_MANAGEMENT_DB_URL:}
        username: ${USER_MANAGEMENT_DB_USER:}
        password: ${USER_MANAGEMENT_DB_PASS:}
      - name: product-catalog
        url: ${PRODUCT_CATALOG_DB_URL:}
        username: ${PRODUCT_CATALOG_DB_USER:}
        password: ${PRODUCT_CATALOG_DB_PASS:}
    dry-run: ${MIGRATION_DRY_RUN:false}
    validate-before-migrate: ${VALIDATE_BEFORE_MIGRATE:true}
    backup-before-migrate: ${BACKUP_BEFORE_MIGRATE:true}

# Logging Configuration
logging:
  level:
    root: INFO
    com.exalt.centralconfiguration.dbmigrations: DEBUG
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/database-migrations.log
    max-size: 10MB
    max-history: 30