# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: ci-cd-templates-db-secret
  namespace: central-configuration
  labels:
    app: ci-cd-templates
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/ci_cd_templates_db"
  username: "ci_cd_templates_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-cd-templates-app-secret
  namespace: central-configuration
  labels:
    app: ci-cd-templates
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
