# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: database-migrations-db-secret
  namespace: central-configuration
  labels:
    app: database-migrations
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/database_migrations_db"
  username: "database_migrations_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-migrations-app-secret
  namespace: central-configuration
  labels:
    app: database-migrations
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
